# Generated by Django 3.0.7 on 2020-06-29 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('more_alike_mvp', '0004_auto_20200629_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
    ]
