# Generated by Django 3.0.7 on 2020-07-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more_alike_mvp', '0006_auto_20200630_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
